name: image_cropper
description: A Flutter plugin for Android, iOS and Web supports cropping images
version: 5.0.1
homepage: https://github.com/hnvn/flutter_image_cropper
publish_to: 'none'
environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutter.plugins.imagecropper
        pluginClass: ImageCropperPlugin

dependencies:
  flutter:
    sdk: flutter
  image_cropper_platform_interface:
    git:
      url: git@github.com:vertex-ly/flutter_image_cropper.git
      path: image_cropper_platform_interface
      ref: android_only

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0